name: Test

on:
  pull_request:
    branches: [main, dev]

env:
  SPEECH_REGION: ${{ secrets.SPEECH_REGION }}
  SPEECH_KEY: ${{ secrets.SPEECH_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: "Install required packages"
      run: |
        sudo apt-get update
        sudo apt-get install build-essential ca-certificates libasound2-dev libssl-dev wget
    
    - name: "Checkout the repository"
      uses: actions/checkout@v6

    - name: "Set up Python"
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - name: "Test with pytest"
      run: |
        uv run pytest
